local Remap = require("gccnvim.keymap")
local nnoremap = Remap.nnoremap

-- Telescope builtin
nnoremap("<C-p>", ":Telescope")
nnoremap("<leader>ps", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ") })
end)
nnoremap("<C-p>", function()
    require('telescope.builtin').git_files()
end)
nnoremap("<leader>pt", function()
    require('telescope.builtin').treesitter()
end)
nnoremap("<leader>pf", function()
    require('telescope.builtin').find_files()
end)
nnoremap("<leader>pb", function()
    require('telescope.builtin').buffers()
end)
nnoremap("<leader>ph", function()
    require('telescope.builtin').help_tags()
end)

-- Telescope custom
nnoremap("<leader>vrm", function()
    require('gccnvim.telescope-reload').reload()
end)
nnoremap("<leader>va", function()
    require('gccnvim.telescope').anime_selector()
end)
nnoremap("<leader>vrr", function()
    require('gccnvim.telescope').refactors()
end)
nnoremap("<leader>gb", function()
    require('gccnvim.telescope').git_branches()
end)
nnoremap("<leader>gw", function()
    require('gccnvim.telescope').extensions.git_worktree.git_worktrees()
end)
nnoremap("<leader>gm", function()
    require('gccnvim.telescope').extensions.git_worktree.create_git_worktree()
end)
